# os yang di gunakan
os:
  - windows
  # Bahasa
  language: php
  # distro
  dist: trusty

  php:
    - '7.1'
    # service yang digunakan
    service:
      - docker
    # grouping task
    jobs:
      include:
      # melakukan testing
        - stage: "taste"
          name: "unit test PHP"
          Script:
          - travis_retry composer self-update
          - travis_retry composer install --prefer-source --no-interaction
          - cp .env.example .env
          - php artisan key:generate
          - vendor/bin/phpunit test/Feature/ExampleTest.php
        # melakukan build images dan publis ke docker hub
        - stage: "Build Docker Image"
          name: "Build Images Docker"
          scrpt: 
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker build -t travis-ci-build-stages-demo .
          - docker images
          - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/pelatihan-cicd-laravel
          - docker push $DOCKER_USERNAME/pelatihan-cicd--laravel